version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol
      - "15672:15672"  # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

  spring-service:
    build:
      context: ./service-1  # Path to the Spring service directory
      dockerfile: Dockerfile
    image: spring-service:1.0
    container_name: spring-service
    depends_on:
      - rabbitmq
    ports:
      - "8080:8080"
    networks:
      - app-network

  kotlin-service:
    build:
      context: ./service-2
      dockerfile: Dockerfile  # Specify Dockerfile if needed
    image: kotlin-service:1.0
    container_name: kotlin-service
    depends_on:
      - rabbitmq
    ports:
      - "8081:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
